name: Build Pioneer Documentation

on:
  push:
    branches:
    - master
    
jobs:
  build-lua-docs:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
        submodules: true
        fetch-depth: 0
        
    - name: Setup git identify
      run: |
        git config --local user.name "Commander Jameson"
        git config --local user.email "CmdrJameson@pioneerspacesim.net"
        
    - name: Merge master into gh-pages
      run: |
        git checkout gh-pages
        git pull --rebase origin master
     
    - name: Download Natural Docs 2.1
      run: |
        wget https://www.naturaldocs.org/download/natural_docs/2.1/Natural_Docs_2.1.zip
        unzip Natural_Docs_2.1.zip
        mv Natural\ Docs NaturalDocs
      
    - name: Generate Lua comments for C++ modules
      run: |
        mkdir gen
        /bin/bash pioneer/scripts/gen_cpp_lua.sh       
        
    - name: Generate Lua Documentation
      run: |
        mkdir -p docs/lua
        rm -rf docs/lua/*
        mono NaturalDocs/NaturalDocs.exe pioneer/nd -i gen/ -i pioneer/data/pigui -i pioneer/data/libs -o html docs/lua
        
    - name: Commit and push changes
      run: |
        MSG=`git log --oneline -1 --pretty=format:%B master`
        git add docs
        git commit -m "Update Lua Documentation (${MSG})"
        git push -f -u origin gh-pages
        
 